import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import AccountsContextProvider from "./components/AccountsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#543310",
              colorInfo: "#543310",
              colorError: "#b33334",
              colorWarning: "#cfa758",
              colorSuccess: "#63b33c",
              colorBgBase: "#fdf7e4",
              colorTextBase: "#543310",
            },
          }}
        >
          <AccountsContextProvider>{children}</AccountsContextProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
